name: gameodoro
description: Pomodoro + Game

publish_to: 'none'

version: 1.0.0+1
environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  collection: ^1.17.0

  # state management
  flutter_hooks: ^0.18.6
  hooks_riverpod: ^2.3.4

  # generators
  riverpod_annotation: ^2.0.1
  freezed_annotation: ^2.2.0
  json_annotation: ^4.8.0

  # UI/UX
  auto_size_text: ^3.0.0
  percent_indicator: ^4.2.3

  # misc
  shared_preferences: ^2.1.0
  audioplayers: ^4.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.3.3
  custom_lint:
  riverpod_generator: ^2.1.3
  riverpod_lint: ^1.1.5
  very_good_analysis: ^4.0.0+1
  freezed: ^2.3.2
  json_serializable: ^6.6.1


flutter:
  uses-material-design: true
  assets:
    - assets/
