name: gameodoro
description: Pomodoro + Game

publish_to: 'none'

version: 1.0.0+1
environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_hooks: ^0.18.6
  hooks_riverpod: ^2.3.4
  cupertino_icons: ^1.0.2
  collection: ^1.17.0
  riverpod_annotation: ^2.0.1
  freezed_annotation: ^2.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.3.3
  custom_lint:
  riverpod_generator: ^2.1.3
  riverpod_lint: ^1.1.5
  very_good_analysis: ^4.0.0+1
  freezed: ^2.3.2


flutter:
  uses-material-design: true
