name: gameodoro
description: Pomodoro + Game

publish_to: 'none'

version: 1.0.0+1
environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  collection: ^1.17.0

  # state management
  flutter_hooks: ^0.18.6
  hooks_riverpod: ^2.3.6

  # generators
  riverpod_annotation: ^2.1.1
  freezed_annotation: ^2.2.0
  json_annotation: ^4.8.0

  # UI/UX
  auto_size_text: ^3.0.0
  percent_indicator: ^4.2.3
  in_app_notification: ^1.1.2

  # misc
  shared_preferences: ^2.1.0
  audioplayers: ^4.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.3.3
  custom_lint:
  riverpod_generator: ^2.2.1
  riverpod_lint: ^1.3.1
  very_good_analysis: ^4.0.0+1
  freezed: ^2.3.2
  json_serializable: ^6.6.1
  flutter_launcher_icons: "^0.13.1"

flutter_launcher_icons:
#  android: "launcher_icon"
#  ios: true
#  image_path: "assets/logo.png"
#  min_sdk_android: 21 # android min sdk min:16, default 21
#  web:
#    generate: true
#    image_path: "assets/logo.png"
#    background_color: "#hexcode"
#    theme_color: "#hexcode"
#  windows:
#    generate: true
#    image_path: "assets/logo.png"
#    icon_size: 48 # min:48, max:256, default: 48
  macos:
    generate: true
    image_path: "assets/icon_macos.png"

flutter:
  uses-material-design: true
  assets:
    - assets/
