name: Android Release

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  build:
    name: Create Android Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Download Android keystore
        id: android_keystore
        uses: timheuer/base64-to-file@v1.0.3
        with:
          fileName: upload-keystore.jks
          encodedString: ${{ secrets.KEYSTORE_BASE64 }}
      - name: Create key.properties
        run: |
          echo "storeFile=${{ steps.android_keystore.outputs.filePath }}" > android/key.properties
          echo "storePassword=${{ secrets.STORE_PASSWORD }}" >> android/key.properties
          echo "keyPassword=${{ secrets.KEY_PASSWORD }}" >> android/key.properties
          echo "keyAlias=${{ secrets.KEY_ALIAS }}" >> android/key.properties
      - uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: "12.x"
          cache: 'gradle'

      - uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.10.0-1.4.pre"
          channel: 'beta'
          cache: true
      - name: Get dependencies
        run: flutter pub get

      - name: Build apk
        run: flutter build apk --verbose --split-per-abi
      - name: Build appbundle
        run: flutter build appbundle
      - name: Upload Android APK arm64 Release
        uses: actions/upload-artifact@v2
        with:
          name: android-apk-arm64
          path: build/app/outputs/flutter-apk/app-arm64-v8a-release.apk
      - name: Upload Android APK arm Release
        uses: actions/upload-artifact@v2
        with:
          name: android-apk-arm
          path: build/app/outputs/flutter-apk/app-armeabi-v7a-release.apk
      - name: Upload Android APK x86 Release
        uses: actions/upload-artifact@v2
        with:
          name: android-apk-x86
          path: build/app/outputs/flutter-apk/app-x86_64-release.apk
      - name: Upload Android AAB Release
        uses: actions/upload-artifact@v2
        with:
          name: android-aab
          path: build/app/outputs/bundle/release/app-release.aab
